# Generated by Django 4.2.16 on 2024-09-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AggregationResult',
        ),
    ]
