# Generated by Django 4.2.16 on 2024-11-15 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0007_alter_accesstoken_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('launcher', '0002_delete_aggregationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jobs', models.ManyToManyField(to='manager.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
