# Generated by Django 4.2.18 on 2025-04-16 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_job_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('launcher', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], max_length=4)),
                ('state', models.CharField(choices=[('C', 'COMPLETED'), ('E', 'Error'), ('R', 'Running'), ('S', 'Submitted')], max_length=64)),
                ('album_id', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(default='')),
                ('runnable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.runnable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
