# Generated by Django 4.2.18 on 2025-04-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0004_aggregationsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregationsubmission',
            name='state',
            field=models.CharField(choices=[('C', 'Completed'), ('E', 'Error'), ('R', 'Running'), ('S', 'Submitted')], max_length=64),
        ),
    ]
