import os

ORTHANC_URL = os.environ['ORTHANC_URL']
ORTHANC_USERNAME = os.environ['ORTHANC_USERNAME']
ORTHANC_PASSWORD = os.environ['ORTHANC_PASSWORD']

SLURM_USER_NAME = os.environ['SLURM_USER_NAME']
SLURM_PRIVATE_KEYFILE = os.environ['SLURM_PRIVATE_KEYFILE']
SLURM_HOST_NAME = os.environ['SLURM_HOST_NAME']

JOB_MANAGER_URL = os.environ['PARADIM_JOB_MANAGER_URL']
DICOM_WEB_URL = os.environ['DICOM_WEB_URL']
KHEOPS_API_URL = os.environ['KHEOPS_API_URL']

PARADIM_TOKEN = os.environ['PARADIM_TECH_TOKEN']

LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO')
