# Generated by Django 4.2.11 on 2024-05-02 14:22

from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, validators=[manager.models.validate_no_space])),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Patient', 'Patient'), ('Study', 'Study'), ('Series', 'Series')], max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(db_comment='Modality abbreviation', max_length=64, unique=True)),
                ('long_name', models.CharField(db_comment='Modality name', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Runnable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('with_gpu', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.app')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.level')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.modality')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.user')),
            ],
            options={
                'unique_together': {('app', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(max_length=256)),
                ('series_instance_uid', models.CharField(max_length=256)),
                ('slurm_id', models.IntegerField(unique=True)),
                ('state', models.CharField(choices=[('APP_ERROR', 'APP_ERROR'), ('TECHNICAL_ERROR', 'TECHNICAL_ERROR'), ('FINISHED', 'FINISHED'), ('RUNNING', 'RUNNING'), ('SUBMITTED', 'SUBMITTED')], max_length=64)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('runnable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.runnable')),
            ],
            options={
                'unique_together': {('series_instance_uid', 'runnable')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.job')),
                ('modality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.modality')),
            ],
        ),
    ]
