# Generated by Django 4.2.11 on 2024-05-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='kheops_album_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='slurm_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('APP_ERROR', 'APP_ERROR'), ('TECHNICAL_ERROR', 'TECHNICAL_ERROR'), ('FINISHED', 'FINISHED'), ('RUNNING', 'RUNNING'), ('SUBMITTED', 'SUBMITTED'), ('NOT_SUBMITTED', 'NOT_SUBMITTED')], max_length=64),
        ),
    ]
