# Generated by Django 4.2.11 on 2024-05-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_job_kheops_album_id_alter_job_slurm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='abbreviation',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('S_fast', 'S_fast'), ('M', 'M'), ('M_fast', 'M_fast'), ('L', 'L'), ('L_fast', 'L_fast'), ('XL', 'XL'), ('XL_fast', 'XL_fast'), ('XXL', 'XXL'), ('XXL_fast', 'XXL_fast')], max_length=8, unique=True),
        ),
    ]
