# Generated by Django 4.2.16 on 2024-09-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_size_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modality',
            name='abbreviation',
            field=models.CharField(max_length=64, unique=True, verbose_name='Modality abbreviation'),
        ),
        migrations.AlterField(
            model_name='modality',
            name='long_name',
            field=models.CharField(max_length=255, verbose_name='Modality name'),
        ),
    ]
