# Generated by Django 4.2.16 on 2024-09-23 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0004_alter_modality_abbreviation_alter_modality_long_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='runnable',
            name='user',
        ),
        migrations.AddField(
            model_name='app',
            name='automatic_run',
            field=models.BooleanField(default=False, verbose_name='Automatic run to new stable series in Orthanc.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('APP_ERROR', 'APP_ERROR'), ('TECHNICAL_ERROR', 'TECHNICAL_ERROR'), ('FINISHED', 'FINISHED'), ('RUNNING', 'RUNNING'), ('SUBMITTED_TO_SLURM', 'SUBMITTED_TO_SLURM'), ('SUBMITTED_TO_QUEUE', 'SUBMITTED_TO_QUEUE')], max_length=64),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
