# Generated by Django 4.2.16 on 2024-09-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_accesstoken_remove_runnable_user_app_automatic_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
