# Generated by Django 4.2.18 on 2025-02-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_accesstoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
