# Generated by Django 4.2.18 on 2025-05-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_job_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedseries',
            name='is_technical_sr',
            field=models.BooleanField(default=False),
        ),
    ]
